POST http://localhost:4000/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "sample10",
    "email": "test8@email.com",
    "password":"hello123"
}

###

GET http://localhost:4000/api/users/ HTTP/1.1
content-type: application/json

###

GET http://localhost:4000/api/users/62d10e9ef2583acc65d88b7c HTTP/1.1
content-type: application/json`

###

DELETE  http://localhost:4000/api/users/62d196a4cf1b40c2e4ffdea7 HTTP/1.1
content-type: application/json`

###
PUT http://localhost:4000/api/users/62f0e6bd6b92a7b049d17222
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

update6
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="_id"

62f0e6bd6b92a7b049d17222
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="dog.jpg"
Content-Type: image/jpg

< ./api/test-images/dog.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

//----------------Game-------------------//

###

POST http://localhost:4000/api/game/level HTTP/1.1
content-type: application/json

{
    "gameLevel": 1,
    "userId": "62f0e3b5712912f5d2538674"
}

###
// Get all
GET http://localhost:4000/api/game/ HTTP/1.1
content-type: application/json


###
// Get one
GET http://localhost:4000/api/game/62f540163539e1058d15aed0 HTTP/1.1
content-type: application/json


###
// Update one
PUT http://localhost:4000/api/game/62f540163539e1058d15aed0 HTTP/1.1
content-type: application/json

{
    "userId": "62f0e3b5712912f5d2538674",
    "gameLevel": 4
}

###